"""Added event table

Revision ID: 032e1263522b
Revises: 101e5c5431a9
Create Date: 2018-12-30 21:23:29.612490

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '032e1263522b'
down_revision = '101e5c5431a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('authenticated', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('email', name='user_pkey')
    )
    # ### end Alembic commands ###
