"""Added soem stuff for user

Revision ID: 3c68587c8a7e
Revises: 30573f3f422d
Create Date: 2018-12-31 13:41:34.796678

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c68587c8a7e'
down_revision = '30573f3f422d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
